
// this file is automatically generated by
export const versions = {
  version: '16.0.69',
  revision: '5075a70',
  branch: 'main',
  shortSHA: '5075a70',
  SHA: '5075a705dfac55e7139ac691cdfad84b3d640fbe',
  lastCommitAuthor: 'Lucas Ribeiro',
  lastCommitTime: 'Mon Jul 31 19:21:55 2023 -0300',
  lastCommitMessage: 'corrigindo animacao',
  copyright: 'Copyright (c) 2023 Lucas Ribeiro'
};