
// this file is automatically generated by
export const versions = {
  version: '16.0.44',
  revision: 'a6f0549',
  branch: 'main',
  shortSHA: 'a6f0549',
  SHA: 'a6f0549bb1ac71b5d6eec7a9eca1316bbaac2535',
  lastCommitAuthor: 'Lucas Ribeiro',
  lastCommitTime: 'Tue Jun 13 20:34:55 2023 -0300',
  lastCommitMessage: 'criando componete de documentacao',
  copyright: 'Copyright (c) 2023 Lucas Ribeiro'
};