
// this file is automatically generated by
export const versions = {
  version: '16.0.56',
  revision: '1f4c624',
  branch: 'main',
  shortSHA: '1f4c624',
  SHA: '1f4c62470ed769dcc2a7499365c69552c33a8289',
  lastCommitAuthor: 'Lucas Ribeiro',
  lastCommitTime: 'Mon Jun 26 22:09:28 2023 -0300',
  lastCommitMessage: 'codando a header do date-picker',
  copyright: 'Copyright (c) 2023 Lucas Ribeiro'
};