export enum InputType {
  checkbox = 'checkbox',
  color = 'color',
  date = 'date',
  datetimeLocal = 'datetime-local',
  email = 'email',
  file = 'file',
  accept = 'accept',
  hidden = 'hidden',
  image = 'image',
  src = 'src',
  month = 'month',
  number = 'number',
  password = 'password',
  radio = 'radio',
  name = 'name',
  range = 'range',
  search = 'search',
  text = 'text',
  time = 'time',
  url = 'url',
  week = 'week',
}
